### PR TITLE
Complete admin account type definition and functionality.

### PR DESCRIPTION
**Pull request by marknemm**
I'm concerned about possible security breaches by having such an 'Admin' account type, but I think it would be nice to enable all of the current leadership in FoodWeb the power of a database admin. Any thoughts or concerns here? We could simply allow the 'Admin' account to act as both Donor and Receiver without other special editing privileges. I've written a detailed summary of the changes below:

Update the account edit form to accommodate the 'Admin' account type.
An admin user can now edit any user's account. The account edit form tracks the original value of the account to merge edit values, instead of relying on session info to provide the original account value of the current user.
An admin can also update any user's password without knowing their old password. The password form mode is now updated based on the current user's account type.
Update the Donor and Receiver tabs to both display 'Admin' type accounts since an 'Admin' can act as any entity in the app.

The server's account-save model has been updated with a safeguard against updating or creating an account with the 'Admin' account type. A developer with direct database access is only able to grant an account the 'Admin' type/access.
It has also had its account and password validation code moved to the shared code space to allow the client to use the same validation.
The server's account save model has also been updated to allow the reset of any user's password (without knowledge of their old password) by an 'Admin' account.

### CODE REVIEW

**Comment by marknemm** [comment]
I apologize if you had trouble attempting to run this branch... I had started working on the Donate Form changes, and separated them out before pushing the changes specific to this branch. When doing this, I happened to miss listing AccountHelper as a provider in the Angular app module. It should work now.

**Comment by BrettSzyjka** [comment]
Everything looks good here except for one issue -
I noticed that there's a bug where if you 

1. sign in as an admin and
2. edit the account of another user and save your changes, then
3. try to edit your own account or that of another user

you get an error that says you aren't authorized to edit the user (even though you are)
It seems like the req.session.account value that is being received by the account API endpoint is that of the edited user, not your own which is causing the problem. I tried to troubleshoot on the client side for a little while but I had some trouble walking through it / getting the debugger working.

Let me know if there's any other info you need

**Comment by marknemm** [comment]
> Everything looks good here except for one issue -
> I noticed that there's a bug where if you
> 
> 1. sign in as an admin and
> 2. edit the account of another user and save your changes, then
> 3. try to edit your own account or that of another user
> 
> you get an error that says you aren't authorized to edit the user (even though you are)
> It seems like the req.session.account value that is being received by the account API endpoint is that of the edited user, not your own which is causing the problem. I tried to troubleshoot on the client side for a little while but I had some trouble walking through it / getting the debugger working.
> 
> Let me know if there's any other info you need

Thanks for reviewing. I know exactly what the error is. I missed a necessary change to the saving of user update data to the current user's session storage on the server. I will apply the change.

**Comment by marknemm** [comment]
> > Everything looks good here except for one issue -
> > I noticed that there's a bug where if you
> > 
> > 1. sign in as an admin and
> > 2. edit the account of another user and save your changes, then
> > 3. try to edit your own account or that of another user
> > 
> > you get an error that says you aren't authorized to edit the user (even though you are)
> > It seems like the req.session.account value that is being received by the account API endpoint is that of the edited user, not your own which is causing the problem. I tried to troubleshoot on the client side for a little while but I had some trouble walking through it / getting the debugger working.
> > Let me know if there's any other info you need
> 
> Thanks for reviewing. I know exactly what the error is. I missed a necessary change to the saving of user update data to the current user's session storage on the server. I will apply the change.

Alright, it's fixed now. I did an interactive rebase to include the change in the original commit. I basically updated the account-controller on the server to write the account save to session storage only if the current user doesn't have an account in their session storage (meaning they have just signed up) or they have an account in session storage with an id that matches the updated account (meaning they just updated their own account).

**Pull request merged**
